"""Add role_id to users

Revision ID: 5b935fd0eaf0
Revises: d65664c84353
Create Date: 2025-12-19 23:31:07.443783

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b935fd0eaf0"
down_revision: Union[str, Sequence[str], None] = "d65664c84353"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("users_role_user_id_fkey"), "users", type_="foreignkey"
    )
    op.create_foreign_key(None, "users", "roles", ["role_id"], ["role_id"])
    op.drop_column("users", "role_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_role_user_id_fkey"),
        "users",
        "roles",
        ["role_user_id"],
        ["role_id"],
    )
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###
