"""create roles table

Revision ID: f5c9d2c043cc
Revises: 5b935fd0eaf0
Create Date: 2025-12-19 23:34:27.762256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c9d2c043cc'
down_revision: Union[str, Sequence[str], None] = '5b935fd0eaf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
               CREATE TABLE IF NOT EXISTS roles
               (
                   role_id   SERIAL PRIMARY KEY,
                   role_name VARCHAR(50) UNIQUE NOT NULL
               );
               """)

    # Добавляем стандартные роли
    op.execute(
        "INSERT INTO roles (role_id, role_name) VALUES (2, 'user') ON CONFLICT (role_id) DO "
        'NOTHING;'
    )
    op.execute(
        "INSERT INTO roles (role_id, role_name) VALUES (1, 'admin') ON CONFLICT (role_id) DO "
        'NOTHING;'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    # ### end Alembic commands ###
