"""ALTER COLUMN order_state SET DEFAULT 'created'

Revision ID: a467261b3af2
Revises: 17f50d957caf
Create Date: 2026-01-21 17:26:58.026230

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a467261b3af2"
down_revision: Union[str, Sequence[str], None] = "17f50d957caf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "order_state", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "order_state", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
