"""create permissions table

Revision ID: 322309dfa841
Revises: 5f1d74f611ed
Create Date: 2026-01-07 16:06:00.913240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "322309dfa841"
down_revision: Union[str, Sequence[str], None] = "5f1d74f611ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("permission_code", sa.String(), nullable=False),
        sa.Column("permission_description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("permission_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("permissions")
    # ### end Alembic commands ###
