"""changed the properties of orders

Revision ID: 17f50d957caf
Revises: 4bf6f34c76cd
Create Date: 2026-01-09 23:00:00.868748

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17f50d957caf"
down_revision: Union[str, Sequence[str], None] = "4bf6f34c76cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "order_state", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "order_state", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
